version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo installing nodejs...
      # - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      #- apt-get install -y nodejs
      - echo "========================= NODE VERSION ======================"
      - node -v
      #- echo installing yarn...
      #- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      #- echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      #- apt install --no-install-recommends yarn
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install --legacy-peer-deps
      # - echo "copying production server config to main file"
      # - cp ./.env.prod ./.env
      # - echo "pre build completed"
  build:
    commands:
      # - echo testing...
      # - echo building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
